---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx
  labels:
    tier: web
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      name: raju
  template:
    metadata:
      labels:
        name: raju
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    name: raju
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---    