---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx
  labels:
    tier: web
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      name: raju
  template:
    labels:
      name: raju
    spec:
      containers:
      - image: nginx:1.23.4
        name: nginx
        ports:
        - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: Loadbalancer
  selector:
    name: raju
  ports:
  - protocal: TCP
    port: 8080
    targetport: 80
---    