apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx
  labels:
    web: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      name: raju
  template:
    metadata:
      labels:     
        name: raju
spec:
  containers:
  - image: nginx
    name: nginx       
