apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx:latest
    name: nginx
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
      type: container  

      