apiVersion: v1
kind: pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - image: nginx:latest
    name: nginx-application
    imagePullPolicey: Always
    volumeMounts:
    - name: logs
      mountPath: /var/logs/nginx
  - image: buzybox
    name: sidecar-container
    imagePullPolicey: Always
    volumeMounts:
    - name: logs
      mountPath: /var/logs/nginx            
  volumes:    
  - name: logs
    emptyDir: {}