apiVersion: v1
kind: Pod
metadata: 
  name: confg-pod
spec:
  containers:
  - image: nginx:latest
    name: nginx
    env:
    - name: test
      valueFrom:
        configMapKeyRef:
          name: raju
          key: love
    - name: test
      valueFrom: 
        configMapKeyRef:
          name: harika
          key: love