apiVersion: v1
kind: Pod
metadata: 
  name: confg-pod
spec:
  containers:
  - image: nginx:latest
    name: nginx
    # env:
    # - name: cource # this is the name of the env
    #   valueFrom:
    #     configMapKeyRef:
    #       name: test
    #       key: cource # this is refrence form the configmaps 
    envFrom:
    - configMapRef:
        name: test 